In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.optimizers import SGD
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("Ionosphere.csv",sep = ',')
data

Saving Ionosphere.csv to Ionosphere (1).csv

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V26,V27,V28,V29,V30,V31,V32,V33,V34,Class
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,1
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,0
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,1
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,0
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,1
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,1
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,1
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,1
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,1

In [ ]:
data.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V26,V27,V28,V29,V30,V31,V32,V33,V34,Class
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480,0.641026
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337,0.480384
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350,0.000000
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000,1.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660,1.000000
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
data.isnull().sum()

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
V11      0
V12      0
V13      0
V14      0
V15      0
V16      0
V17      0
V18      0
V19      0
V20      0
V21      0
V22      0
V23      0
V24      0
V25      0
V26      0
V27      0
V28      0
V29      0
V30      0
V31      0
V32      0
V33      0
V34      0
Class    0
dtype: int64

In [ ]:
X = data.iloc[:,:34]
X

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V25,V26,V27,V28,V29,V30,V31,V32,V33,V34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.95378,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.94520,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.93988,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.91050,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,0.86467,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151

In [ ]:
Y = data.iloc[:,34:]
Y

     Class
0        1
1        0
2        1
3        0
4        1
..     ...
346      1
347      1
348      1
349      1
350      1

[351 rows x 1 columns]

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 20 , random_state = 1)

In [ ]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([[ 0.51965931],
       [ 0.97084571],
       [ 0.25157056],
       [ 1.03990313],
       [ 0.6734635 ],
       [ 0.98580783],
       [ 0.97624223],
       [ 0.68764263],
       [ 0.26146304],
       [ 0.58858414],
       [ 0.93268949],
       [ 0.97244353],
       [ 0.46363814],
       [ 0.83106535],
       [ 0.26816449],
       [ 0.61439933],
       [ 0.56169653],
       [ 0.52197499],
       [ 0.75013736],
       [-0.12278544]])

In [ ]:
error = mean_absolute_error(y_pred,Y_test)
print(error)

0.26550542000545735

In [ ]:
score = r2_score(y_pred,Y_test)
print(score)

-0.19771402279987793

In [ ]:
model = SGDRegressor(loss='squared_error',penalty='l2', alpha=0.0001)
model.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SGDRegressor()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0.40770013, 0.92376929, 0.27286972, 1.01087067, 0.68975844,
       0.94829143, 0.90880701, 0.72693914, 0.20907827, 0.59726862,
       0.92680335, 0.93527809, 0.4294679 , 0.81199129, 0.23324827,
       0.71351905, 0.57616681, 0.54642838, 0.7533373 , 0.12935812])

In [ ]:
error = mean_absolute_error(y_pred,Y_test)
print(error)

0.2674333488138655

In [ ]:
score = r2_score(y_pred,Y_test)
print(score)

-0.4790921004921276

In [ ]:
def SGD(data, learning_rate=0.2, n_epochs=1000, k=40):
    w = np.random.randn(1,data.shape[1]-1)
    b = 0
    epoch=1
    
    while epoch <= n_epochs:
        temp = data.sample(k)
        y = np.array(temp["Class"])
        x  =np.array(temp.drop("Class",axis=1))
        L_w = w
        L_b = b
        loss = 0
        y_pred = []

        for i in range(k): 
            L_w = (-2/k * x[i]) * (y[i] - np.dot(x[i],w.T) - b)
            L_b = (-2/k) * (y[i] - np.dot(x[i],w.T) - b)
            w = w - learning_rate * L_w
            b = b - learning_rate * L_b
            
        epoch += 1
        learning_rate = learning_rate/1.02
        
    return w,b

In [ ]:
def predict(x,w,b):
    y_pred = []
    for i in range(len(x)):
        y = np.asscalar(np.dot(w,x[i])+b)
        y_pred.append(y)
    return np.array(y_pred)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

w,b = SGD(data)
x_test = np.array(X_test)
y_test = np.array(Y_test)

from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
x_test = scaler.fit_transform(X_test)
y_pred = predict(x_test,w,b)

print('Mean Squared Error :',mean_squared_error(y_test, y_pred))

Mean Squared Error : 1.2810861308238193

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  after removing the cwd from sys.path.

In [ ]:
def batches(X, y, batch_size):
    mini_batches = []
    data = np.hstack((X, y))
    np.random.shuffle(data)
    n_minibatches = data.shape[0] // batch_size
    i = 0
 
    for i in range(n_minibatches + 1):
        mini_batch = data[i * batch_size:(i + 1)*batch_size, :]
        X_mini = mini_batch[:, :-1]
        Y_mini = mini_batch[:, -1].reshape((-1, 1))
        mini_batches.append((X_mini, Y_mini))
    if data.shape[0] % batch_size != 0:
        mini_batch = data[i * batch_size:data.shape[0]]
        X_mini = mini_batch[:, :-1]
        Y_mini = mini_batch[:, -1].reshape((-1, 1))
        mini_batches.append((X_mini, Y_mini))
    return mini_batches

In [ ]:
def SGD(data, learning_rate=0.01, n_epochs=1000, k=10, batch_size=40):
    w = np.random.randn(1,data.shape[1]-1)
    b = 0
    epoch=1
    
    while epoch <= n_epochs:
        temp = data.sample(k)
        y = temp.iloc[:,34:].values.tolist()
        x = np.array(temp.drop("Class",axis=1))
        L_w = w
        L_b = b
        
        for i in range(k):
            mini_batches = batches(x, y, batch_size)
            for mini_batch in mini_batches:
                x, y = mini_batch
                L_w = (-2/k * x[i]) * (y[i] - np.dot(x[i],w.T) - b)
                L_b = (-2/k) * (y[i] - np.dot(x[i],w.T) - b)
                w = w - learning_rate * L_w
                b = b - learning_rate * L_b
            
        epoch += 1
        learning_rate = learning_rate/1.02
        
    return w,b

In [ ]:
def predict(x,w,b):
    y_pred = []
    for i in range(len(x)):
        y = np.asscalar(np.dot(w,x[i])+b)
        y_pred.append(y)
    return np.array(y_pred)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

w,b = SGD(data)
x_test = np.array(X_test)
y_test = np.array(Y_test)

from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
x_test = scaler.fit_transform(X_test)
y_pred = predict(x_test,w,b)

print('Mean Squared Error :',mean_squared_error(y_test, y_pred))

Mean Squared Error : 9.817512495623223

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  after removing the cwd from sys.path.

# Conclusion:

Mini Batch stochastic gradient descent is better than stochastic gradient descent as it has less error.